run:
  concurrency: 1
  timeout: 1m
  tests: false
  go: "1.22"

issues:
  exclude-dirs:
    - example
  max-issues-per-linter: 1000
  max-same-issues: 1000
  exclude-use-default: false
  exclude-rules:
    - linters:
        - revive
      text: "package-comments|RawFormulaVal|ErrLoadFullModelFromFile"
    - linters:
        - gocritic
      text: "dupSubExpr:"
  exclude:
    - "ST1000: at least one file in a package should have a package comment"

linters-settings:
  funlen:
    lines: 80

  staticcheck:
    checks: ["all"]

  dupl:
    threshold: 50

  stylecheck:
    checks: ["all"]

  dogsled:
    max-blank-identifiers: 2

  govet:
    enable-all: true

  godot:
    scope: all

  gosimple:
    checks: ["all"]

linters:
  disable-all: true
  enable:
    - dogsled
    - errcheck
    - copyloopvar
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - revive
    - godot

  presets:
    - bugs
    - comment
    - format
    - unused
