name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Download CatBoost Library
        run: |
          sudo wget -q "https://github.com/catboost/catboost/releases/download/v1.2.5/libcatboostmodel.so" -O /usr/local/lib/libcatboostmodel.so

      - name: Run unit-tests
        run: |
          go test -v ./...

  Inference:
    needs: [Testing]
    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Download CatBoost Library
        run: |
          ls -la /usr/local/
          sudo wget -q "https://github.com/catboost/catboost/releases/download/v1.2.5/libcatboostmodel.so" -O /usr/local/lib/libcatboostmodel.so
          sudo wget -q "https://github.com/catboost/catboost/releases/download/v1.2.5/libcatboostmodel.dylib" -O /usr/local/lib/libcatboostmodel.dylib

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4.8.0
        with:
          python-version: "3.9"

      - name: Install Python requirements
        run: pip install -r requirements.txt

      - name: Train (Python)
        run: make train

      - name: Predict (Golang)
        run: make predict
