name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CATBOOST_LIBRARY_PATH: ${{ github.workspace }}/libcatboostmodel.so
      CGO_ENABLED: 1

    steps:
      - uses: actions/checkout@v4

      - name: Download CatBoost Library
        run: |
          wget "https://github.com/catboost/catboost/releases/download/v1.2.5/libcatboostmodel.so" -O libcatboostmodel.so

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Test
        run: |
          env
          ls -la
          go test -v ./...
