name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: seemeai/catboost:1.2.5
    steps:
      - uses: actions/checkout@v4

      # - name: Download CatBoost Library
      #   run: |
      #     sudo wget "https://github.com/catboost/catboost/releases/download/v1.2.5/libcatboostmodel.so" -O /usr/local/lib/libcatboostmodel.so
      #     ls -la /usr/local/lib/

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Test
        run: |
          go test -v ./...
