name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download CatBoost Library
        run: |
          sudo wget "https://github.com/catboost/catboost/releases/download/v1.2.5/libcatboostmodel.so" -O libcatboostmodel.so
          ls -la /usr/local/lib/

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Test
        run: |
          sudo chmod 777 libcatboostmodel.so
          ls -la 
          CATBOOST_LIBRARY_PATH=libcatboostmodel.so go test -v ./...
