name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]

jobs:
  Testing:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Download CatBoost Library
        run: |
          sudo wget -q "https://github.com/catboost/catboost/releases/download/v1.2.5/libcatboostmodel.so" -O /usr/local/lib/libcatboostmodel.so

      - name: Run unit-tests
        run: |
          go test -v ./...
